import Head from "next/head";
import { useState } from "react";
import Router from "next/router";
import Link from "next/link";
import { Form, Row } from "react-bootstrap";
import verifyAuth from "./HOC/verifyAuth.jsx";
import RestorePassWordButton from "../components/ModalComponents/RestorePassword/index.js";
import { commonService } from "../service/HttpNoTokenRequired/commonService.js";
import Swal from "sweetalert2";

const initialState = {
  email: "",
  password: "",
};

function Home() {
  const [login, setLogin] = useState(initialState);
  const { startLogIn } = commonService();

  const handleChangeInput = (e) => {
    const { name, value } = e.target;
    setLogin({ ...login, [name]: value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const res = await startLogIn(login);

    if (res.status !== 200) {
      Swal.fire({
        title: "Error!",
        text: "Please provide a valid email address and password.",
        icon: "error",
        confirmButtonText: "Ok",
      });
    } else {
      Swal.fire({
        title: "Good!",
        icon: "success",
        timer: 1500,
      });
      Router.reload(window.location.pathname);
    }
  };

  return (
    <>
      <Head>
        <title>Antonio Training</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="limiter">
        <div className="container-login100">
          <div className="wrap-login100">
            <div className="login100-form">
              <div className="card">
                <div className="card-header bg-primary text-white text-center">
                  Log in to your account
                </div>
                <div className="card-body">
                  <Form onSubmit={handleSubmit}>
                    <Row className="mb-4">
                      <Form.Group className="mb-4">
                        <Form.Label>Email</Form.Label>
                        <Form.Control
                          onChange={handleChangeInput}
                          name="email"
                          className="form-control "
                          type="email"
                          placeholder="Email address"
                        />
                      </Form.Group>

                      <Form.Group className="mb-4 ">
                        <Form.Label>Password</Form.Label>
                        <Form.Control
                          onChange={handleChangeInput}
                          name="password"
                          className="form-control "
                          type="password"
                          placeholder="Password"
                          autoComplete="on"
                        />
                      </Form.Group>
                      <div className="text-center">
                        <button type="submit" className="btn btn-primary  ">
                          Sign in
                        </button>
                      </div>
                    </Row>
                  </Form>
                  <div className="text-center p-t-46 ">
                    <Link href="/register">
                      <a className="txt2">o Create a new account</a>
                    </Link>
                  </div>
                  <div className="text-center p-t-46 ">
                    <RestorePassWordButton />
                  </div>
                </div>
              </div>
            </div>
            <div className="login100-more" />
          </div>
        </div>
      </div>
    </>
  );
}

export default verifyAuth(Home);
